### ISSUE TITLE
Shared key generation failed. Error: AES encryption failed in final stage.

### ISSUE THREAD

**Issue by bigmakkmclovin** [vpaeder/telink_light_cpp#1]
Thank you for the library!!

This is a bit of a cross post. I think I'm getting a similar issue in the dimond library, although it's easier to debug there: https://github.com/google/python-dimond/issues/2

The error here is ```Shared key generation failed. Error: AES encryption failed in final stage.```

It looks like there is a successful connection but only one byte is returned from the device.  Thank you for any help!

**Comment by vpaeder** [comment]
The AES encryption routine wants a n x 16 byte long chain and won't pad, so if it's fed with 1 byte it will throw this error. As to why your lamp returns this, I'd say it's a password problem.
I had a quick look at one HaoDeng app (tagged v1.4.5) with JADX. What I think is the login code makes sense, but it's duplicate. There's one version with hardcoded strings and one that takes variables. Since you say the hardcoded strings don't work, it probably uses the 2nd one with values initialized I don't know where. Debugging the app with Android Studio would probably be easier.

**Comment by bigmakkmclovin** [comment]
Awesome! Thanks! I debugged and got what seems to be the right username and password. The lamp is now returning the full 16 byte long chain. It gets connected and gets to the last step in the test loop to change the light colors. Unfortunately, nothing is happening with the light. I'm going to keep checking for different username/pw, but is there anything else I should check?

Edit: It looks correct. It is the variables used in the bitwise encryption. They are named meshKey and meshPassword by an object that stores them. There is also a meshLTK (long-term key it looks like) if that helps. Any tips on debugging this would be much appreciated!

**Comment by vpaeder** [comment]
If the lamp answers with a decipherable chain then you likely got the right credentials. It's possible that it uses different opcodes. In Briloner's case the on/off opcode is 0xF0, which is not what's defined in Opcode.java (0xD0).
You can try something like:
`    from pytelink import TelinkLight`
`    ble_light = TelinkLight(address = "AA:BB:CC:DD:EE:FF", name = "DevName", password = "Password")`
`    ble_light.connect()`
`    ble_light.send_packet(command = 0xD0, data = "\x01\x00\x00")`

and play with command and data values.

**Comment by bigmakkmclovin** [comment]
It works!! Thank you for all your help!!

**Comment by zougloub** [comment]
Thank you for documenting the issue.
I had gotten [lights](https://www.amazon.ca/gp/product/B07SKNKP4J) whose companion app is [Mesh Lamp](https://play.google.com/store/apps/details?id=com.telink.bluetooth.mesh_lamp) and after looking to drive them from something else than the app and finding [python-dimond](https://github.com/google/python-dimond) and this code, I got myself facing the same authentication issue. In this case the hard-coded mesh name is "Fulife" and password is "2846". Then opcodes are different too.

**Comment by vpaeder** [comment]
Ok thanks a lot for sharing this info
